# render.yaml
services:
  - type: web
    name: medmap-booking-service
    runtime: node
    rootDir: services/booking
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: "https://medmap-f4ob.onrender.com"
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false