# Generated by Django 6.0 on 2025-12-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_fee_booking_consultation_fee_and_more'),
        ('doctors', '0007_alter_doctorschedule_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('doctor', 'appointment_date', 'appointment_time')},
        ),
    ]
